name = "tony-agent"
main = "chat-widget/worker.js"
compatibility_date = "2025-01-01"

[env.staging]
vars = { 
  PERSONA_URL = "https://<REFLECTIV>.github.io/assets/chat/persona.json",
  KNOWLEDGE_URL = "https://<REFLECTIV>.github.io/assets/chat/knowledge/about-tony.md",
  USE_KEYWORD_FILTER = "true",
  ALLOWED_ORIGINS = "https://<REFLECTIV>.github.io,https://<TONY_MAIN>.github.io",
  GROQ_URL = "https://api.groq.com/openai/v1/chat/completions",
  GROQ_MODEL = "llama-3.1-70b-versatile",
  GROQ_API_KEY = "[REDACTED]"
}

[env.production]
vars = { 
  PERSONA_URL = "https://<TONY_MAIN>.github.io/assets/chat/persona.json",
  KNOWLEDGE_URL = "https://<TONY_MAIN>.github.io/assets/chat/knowledge/about-tony.md",
  USE_KEYWORD_FILTER = "true",
  ALLOWED_ORIGINS = "https://<TONY_MAIN>.github.io,https://<REFLECTIV>.github.io",
  GROQ_URL = "https://api.groq.com/openai/v1/chat/completions",
  GROQ_MODEL = "llama-3.1-70b-versatile",
  GROQ_API_KEY = "[REDACTED]"
}
