name = "tony-agent"
main = "chat-widget/worker.js"
compatibility_date = "2025-01-01"

[env.staging]
vars = { 
  PERSONA_URL = "https://reflectivei.github.io/reflectiv-ai/assets/chat/persona.json",
  KNOWLEDGE_URL = "https://reflectivei.github.io/reflectiv-ai/assets/chat/knowledge/about-tony.md",
  USE_KEYWORD_FILTER = "true",
  ALLOWED_ORIGINS = "https://reflectivei.github.io/reflectiv-ai",
  GROQ_URL = "https://api.groq.com/openai/v1/chat/completions",
  GROQ_MODEL = "llama-3.1-70b-versatile"
}
# Set secret separately:
#   wrangler secret put GROQ_API_KEY --env staging

[env.production]
vars = { 
  PERSONA_URL = "https://tonyabdelmalak.github.io/<main-repo>/assets/chat/persona.json",
  KNOWLEDGE_URL = "https://tonyabdelmalak.github.io/<main-repo>/assets/chat/knowledge/about-tony.md",
  USE_KEYWORD_FILTER = "true",
  ALLOWED_ORIGINS = "https://tonyabdelmalak.github.io/<main-repo>",
  GROQ_URL = "https://api.groq.com/openai/v1/chat/completions",
  GROQ_MODEL = "llama-3.1-70b-versatile"
}
# Set secret separately:
#   wrangler secret put GROQ_API_KEY --env production
