name = "tony-agent"
main = "chat-widget/worker.js"
compatibility_date = "2025-01-01"

# Defaults used if an env value isn't specified
[vars]
USE_KEYWORD_FILTER = "true"

# ---------- STAGING (Reflectiv) ----------
[env.staging]
vars = {
  # Public URLs to persona/knowledge hosted on Reflectiv staging GitHub Pages
  PERSONA_URL   = "https://reflectivei.github.io/reflectiv-ai/assets/chat/persona.json",
  KNOWLEDGE_URL = "https://reflectivei.github.io/reflectiv-ai/assets/chat/knowledge/about-tony.md",

  # CORS: only allow your staging site origin
  ALLOWED_ORIGINS = "https://reflectivei.github.io",

  # Groq API settings (use any staging model you like)
  GROQ_URL   = "https://api.groq.com/openai/v1/chat/completions",
